#!/usr/bin/env bash
# A bash script that install nginx web server

sudo apt update
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
