#!/usr/bin/env bash
# A bash script that install nginx web server

sudo apt update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
