#!/usr/bin/env bash
# A Bash script that configures your Nginx server to have a custom
# 404 page that contains the string 'Ceci n'est pas une page'

apt-get update
apt-get -y install nginx
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sed -i '53i \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sed -i "57i \\\n\terror_page 404 = @error404;\n\n\tlocation @error404 {\n\t\tdefault_type text/html;\n\t\treturn 404 'Ceci n\\\'est pas une page\\\n';\n\t}" /etc/nginx/sites-available/default
#sudo sed -i "53i \\\n\terror_page 404 = @error404;\n\n\tlocation @error404 {\n\t\tdefault_type text/html;\n\t\treturn 404 '<h1>Ceci n\\\'est pas une page</h1>';\n\t}" /etc/nginx/sites-available/defaultl
nginx -t
service nginx reload
