#!/usr/bin/env bash
# A Bash script that configures your Nginx server to have a custom
# 404 page that contains the string 'Ceci n'est pas une page'

ADD301_REDIRECT="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
ADD404_NOTFOUND="\\\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\tinternal;\n\t}"

apt-get update
apt-get -y install nginx

echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

sed -i "53i $ADD301_REDIRECT" /etc/nginx/sites-available/default
sed -i "57i $ADD404_NOTFOUND" /etc/nginx/sites-available/default

nginx -t
service nginx reload
