#!/usr/bin/env bash
# A Bash script that configures your Nginx server to have a custom
# 404 page that contains the string 'Ceci n'est pas une page'

sed -i "53i \\\n\terror_page 404 = @error404;\n\n\tlocation @error404 {\n\t\tdefault_type text/html;\n\t\treturn 404 'Ceci n\\\'est pas une page\\\n';\n\t}" /etc/nginx/sites-available/default
#sudo sed -i "53i \\\n\terror_page 404 = @error404;\n\n\tlocation @error404 {\n\t\tdefault_type text/html;\n\t\treturn 404 '<h1>Ceci n\\\'est pas une page</h1>';\n\t}" /etc/nginx/sites-available/default
nginx -t
service nginx reload
