#!/usr/bin/env bash
# Make Nginx listen on port 80

#sudo apt-get update
#sudo apt-get -y install nginx
#sudo nginx
#sudo service nginx restart


sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
