#!/usr/bin/env bash
#  Displays a list of currently running process
#+ Must show all processes, for all users, including those which might not have a TTY
#+ Display in a user-oriented format, show process hierarchy.

ps -aux --forest
