#!/usr/bin/env bash
#   A bash script that displays "Best School 10 times, but for the 9th
#+  interation, display "Best School" and then Hi on a new line

i=1
n=10
while ((i <= n)); do
    echo "Best School"
    if [ "$i" -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
