#!/usr/bin/env bash
# A bash script that displays the time for 12 hours and 59 minutes

i=0
hr=12
min=59
while ((i <= hr)); do
    echo "Hour: $i"
    j=1
    while ((j <= min)); do
        echo "$j"
        ((j++))
    done
    ((i++))
done
