#!/usr/bin/env bash
# Install ufw, enable support for IPv6, allow tcp ports 22, 443, 80

# Install ufw, support IPv6
sudo apt-get -y install ufw
sudo sed -i "s/IPV6=no/IPV6=yes/" /etc/default/ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming

# Allowed TCP ports
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

# Enable ufw
sudo ufw enable
