#!/usr/bin/env bash
#  A Bash script that configures an Ubuntu 
#+ server with the below requirements.
#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts ~/hosts.new
#sed -i -e '/localhost/s/^[0-9].*$/127.0.0.2\tlocalhost/' -e '/facebook.com/s/^[1-9].*$/8.8.8.8\tfacebook.com/' ~/hosts.new
sed -i s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
