#!/usr/bin/env bash
# A script that changes nginx user and
# nginx must be listening on all active IPs on port 8080

# Grant the necessary permissions to user nginx for the Nginx directories
sudo chmod 700 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf

# Replace user www-data with nginx
sudo sed -i "s/www-data/nginx/" /etc/nginx/nginx.conf

# Replace port 80 with 8080
sudo sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-enabled/default

# Restart nginx
pkill apache2
sudo -u nginx service nginx restart
